// Ficheiro de Configuração Gerado Automaticamente
const STORAGE_DATA_KEY = "appConfigData_v2.0";

const DADOS_PADRAO = {
  lojas: [
    {"formato":"Hiper","loja":"008-Gaia"},
    {"formato":"Hiper","loja":"009-Coimbra"},
    {"formato":"Hiper","loja":"010-Viseu"},
    {"formato":"Hiper","loja":"012-Almada"},
    {"formato":"Hiper","loja":"013-Torres Vedras"},
    {"formato":"Hiper","loja":"014-Amadora"},
    {"formato":"Hiper","loja":"016-Matosinhos"},
    {"formato":"Hiper","loja":"017-Guimarães"},
    {"formato":"Hiper","loja":"018-Paço de Arcos"},
    {"formato":"Hiper","loja":"019-Coina"},
    {"formato":"Hiper","loja":"021-Evora"},
    {"formato":"Hiper","loja":"022-Cascais Nascente"},
    {"formato":"Hiper","loja":"023-Portimão"},
    {"formato":"Hiper","loja":"024-Amoreiras"},
    {"formato":"Hiper","loja":"025-Alfragide"},
    {"formato":"Hiper","loja":"026-Maia"},
    {"formato":"Hiper","loja":"027-Setúbal"},
    {"formato":"Hiper","loja":"028-Castelo Branco"},
    {"formato":"Hiper","loja":"029-Alverca"},
    {"formato":"Hiper","loja":"030-Santo Tirso"},
    {"formato":"Hiper","loja":"031-Famalicao"},
    {"formato":"Hiper","loja":"032-Aveiro"},
    {"formato":"Hiper","loja":"033-Faro"},
    {"formato":"Hiper","loja":"034-Figueira da Foz"},
    {"formato":"Hiper","loja":"035-Gondomar"},
    {"formato":"Hiper","loja":"036-Vila Real"},
    {"formato":"Hiper","loja":"038-Sintra"},
    {"formato":"Hiper","loja":"039-Vila do Conde"},
    {"formato":"Super","loja":"52-C. DA RAINHA"},
    {"formato":"Hiper","loja":"053-Olhão"},
    {"formato":"Super","loja":"54-GUARDA"},
    {"formato":"Super","loja":"57-CAMPERA"},
    {"formato":"Super","loja":"58-FARO MERCADO"},
    {"formato":"Super","loja":"62-EIRAS"},
    {"formato":"Hiper","loja":"062-Eiras"},
    {"formato":"Hiper","loja":"063-Lagoa"},
    {"formato":"Super","loja":"65-CANIDELO"},
    {"formato":"Prox","loja":"402-UP LX JOÃO XXI"},
    {"formato":"Prox","loja":"403-UP LX PASCOAL DE MELO"},
    {"formato":"Prox","loja":"404-UP LX DUQUE AVILA"},
    {"formato":"Prox","loja":"405-UP RUA DOS PESCADORES"},
    {"formato":"Prox","loja":"406-UP DAM MONTEIRO-GRAÇA"},
    {"formato":"Prox","loja":"407-UP D. PEDRO IV-QUELUZ"},
    {"formato":"Prox","loja":"408-UP C QUINTINHA-CAMPOLIDE"},
    {"formato":"Prox","loja":"409-UP ALMIRANTE REIS"},
    {"formato":"Prox","loja":"410-UP PENHA DE FRANCA"},
    {"formato":"Prox","loja":"411-UP MAJOR NEUTEL ABREU"},
    {"formato":"Prox","loja":"412-UP PRACA GIL VICENTE-ALMADA"},
    {"formato":"Prox","loja":"413-UP AV REPUBLICA"},
    {"formato":"Prox","loja":"414-UP COLUMBANO BORDALO PINHEIRO"},
    {"formato":"Prox","loja":"416-UP F NAMORA ODIVELAS"},
    {"formato":"Prox","loja":"417-UP DNUNO ÁLVARES PER-ALMADA"},
    {"formato":"Prox","loja":"419-UP COMBAT GRANDE GUERRA_ALGES"},
    {"formato":"Prox","loja":"420-UP PCT JOSÉ FONTANA_BOBADELA"},
    {"formato":"Prox","loja":"421-UP ALMIRANTE REIS 203"},
    {"formato":"Prox","loja":"422-UP R DA BENEFICENCIA"},
    {"formato":"Prox","loja":"423-UP ALM BENTO GONCALVES"},
    {"formato":"Prox","loja":"424-UP LX LUIS MACEDO"},
    {"formato":"Prox","loja":"425-UP ALM LUIS QUEIROZ"},
    {"formato":"Prox","loja":"427-UP ESTRADA BENFICA 418"},
    {"formato":"Prox","loja":"429-UP ADELAIDE CABETE CARNIDE"},
    {"formato":"Prox","loja":"430-UP RUA ELIAS GARCIA AMADORA"},
    {"formato":"Prox","loja":"432-UP PRACETA NOSSA SRA NAVEGANTES"},
    {"formato":"Prox","loja":"433-UP OSCAR MONTEIRO TORRES"},
    {"formato":"Prox","loja":"434-UP AV D JOAO II"},
    {"formato":"Prox","loja":"435-UP RUA JOSE RICARDO"},
    {"formato":"Prox","loja":"436-UP RUA FERREIRA BORGES"},
    {"formato":"Prox","loja":"437-UP RUA PEDRO NUNES"},
    {"formato":"Prox","loja":"438-UP RUA VISCONDE SANTAREM"},
    {"formato":"Prox","loja":"439-UP CALÇADA DA AJUDA"},
    {"formato":"Prox","loja":"440-UP ALVARES CABRAL"},
    {"formato":"Prox","loja":"441-UP FABRICA 1921"},
    {"formato":"Prox","loja":"442-UP MORAIS SOARES"},
    {"formato":"Prox","loja":"443-UP C REIS (Cacilhas)"},
    {"formato":"Prox","loja":"444-UP C.G.GUERRA (VFX)"},
    {"formato":"Prox","loja":"445-UP CONDE REDONDO"},
    {"formato":"Prox","loja":"446-UP BJ CARAÇA (PORTO)"},
    {"formato":"Prox","loja":"447-UP PÇ EXÉRCITO LIBERTADOR"},
    {"formato":"Prox","loja":"449-UP RUA CAMÕES PORTO"},
    {"formato":"Prox","loja":"450-UP CAMPO ALEGRE PORTO"},
    {"formato":"Prox","loja":"451-UP R CAPITÃO LEITÃO ALMADA"},
    {"formato":"Prox","loja":"452-UP R VENEZUELA PORTO"},
    {"formato":"Prox","loja":"453-UP R MARECHAL SALDANHA PORTO FOZ"},
    {"formato":"Prox","loja":"454-UP AV BOAVISTA PORTO"},
    {"formato":"Prox","loja":"455-UP AV D MANUEL II MAIA"},
    {"formato":"Prox","loja":"458-UP RINCHOA"},
    {"formato":"Prox","loja":"459-UP LUMIAR - ALAMEDA DAS LINHAS DE TORRES"},
    {"formato":"Super","loja":"460-UP TIRES"},
    {"formato":"Super","loja":"461-UP B. BANHEIRA - RUA LIBERDADE"},
    {"formato":"Prox","loja":"462-UP LARGO GRAÇA"},
    {"formato":"Prox","loja":"A01-MA Costa Cabral, Paranhos"},
    {"formato":"Prox","loja":"A02-MA Nova Seixo, Custóias"},
    {"formato":"Prox","loja":"A03-MA Pires Lima, Paranhos"},
    {"formato":"Prox","loja":"A04-MA Liberdade, Braga Centro"},
    {"formato":"Prox","loja":"A05-MA Marquês Pombal, Póvoa Varzim"},
    {"formato":"Prox","loja":"A06-MA 9 Abril, Paranhos"},
    {"formato":"Prox","loja":"A07-MA José Sampaio, Guimarães Centro"},
    {"formato":"Prox","loja":"A08-MA Firmeza, Bonfim"},
    {"formato":"Prox","loja":"A09-MA Vila D'Este, Vilar Andorinho"},
    {"formato":"Prox","loja":"A10-MA Gonçalo Mendes Maia, Pedrouços"},
    {"formato":"Super","loja":"A11-SU D António Castro Meireles, Ermesinde"},
    {"formato":"Prox","loja":"A12-MA Dr Fernando Aroso, Matosinhos Centro"},
    {"formato":"Prox","loja":"A13-MA Praia, Apúlia"},
    {"formato":"Prox","loja":"A14-MA Lourenço Marques, Ermesinde"},
    {"formato":"Prox","loja":"A15-MA República, Buarcos"},
    {"formato":"Prox","loja":"A16-MA Fernandes Tomás, Porto Centro"},
    {"formato":"Prox","loja":"A17-MA Cedofeita, Porto Centro"},
    {"formato":"Prox","loja":"A18-MA Pr Exército Libertador, Porto Centro"},
    {"formato":"Prox","loja":"A19-MA Ferreirinha, Peso Régua"},
    {"formato":"Super","loja":"A20-SU D Pedro V, Bougado"},
    {"formato":"Super","loja":"A21-SU José Régio, Ermesinde"},
    {"formato":"Super","loja":"A23-SU Lugar Sernados, Feitosa"},
    {"formato":"Super","loja":"A24-SU Retail Park, Esgueira"},
    {"formato":"Super","loja":"A25-SU Comend António Mª Lopes, Sto Tirso"},
    {"formato":"Super","loja":"A27-SU Malaposta, Mogofores"},
    {"formato":"Super","loja":"A28-SU Ribeirinha, Sta Maria Lamas"},
    {"formato":"Super","loja":"A29-SU José Cardoso Castro, Fafe"},
    {"formato":"Super","loja":"A30-SU Vasco Gama, Vilar Andorinho"},
    {"formato":"Super","loja":"A31-SU D Afonso Henriques, Rio Tinto"},
    {"formato":"Super","loja":"A32-SU Cândido Reis, Custóias"},
    {"formato":"Super","loja":"A33-SU Poesia, Fânzeres"},
    {"formato":"Super","loja":"A34-SU Ponte Pedrinha, Braga Centro"},
    {"formato":"Prox","loja":"A35-MA S Bento, Estrela"},
    {"formato":"Prox","loja":"A37-MA Guerra Junqueiro, Arroios"},
    {"formato":"Prox","loja":"A38-MA Major Afonso Pala, Carnaxide"},
    {"formato":"Prox","loja":"A39-MA D Nuno Álvares Pereira, Venteira"},
    {"formato":"Prox","loja":"A40-MA Heliodoro Salgado, Almada"},
    {"formato":"Prox","loja":"A41-MA Duque Loulé, Sto António"},
    {"formato":"Prox","loja":"A42-MA Elias Garcia, Queluz"},
    {"formato":"Prox","loja":"A43-MA Saraiva Carvalho, Campo Ourique"},
    {"formato":"Prox","loja":"A44-MA Est Mem Martins 274, Algueirão"},
    {"formato":"Prox","loja":"A45-MA Sacadura Cabral, S Domingos Rana"},
    {"formato":"Prox","loja":"A46-MA Urb Qta Sto Amaro, Laranjeiro"},
    {"formato":"Prox","loja":"A47-MA Vitor Gallo, Marinha Grande"},
    {"formato":"Prox","loja":"A48-MA Infante D Pedro, Alverca"},
    {"formato":"Prox","loja":"A49-MA S Paulo, Misericórdia"},
    {"formato":"Prox","loja":"A50-MA Calvário, Alcântara"},
    {"formato":"Prox","loja":"A52-MA Boa Hora, Ajuda"},
    {"formato":"Prox","loja":"A53-MA 1 Maio, Camarate"},
    {"formato":"Prox","loja":"A54-MA Dr Dário Gandra Nunes, Venteira"},
    {"formato":"Prox","loja":"A55-MA Calhariz, Misericórdia"},
    {"formato":"Prox","loja":"A56-MA Forno Tijolo, Arroios"},
    {"formato":"Prox","loja":"A57-MA Padre Manuel Nóbrega, Areeiro"},
    {"formato":"Prox","loja":"A58-MA Prof Dr Augusto Abreu Lopes, Odivelas"},
    {"formato":"Prox","loja":"A59-MA Qta Campo, Corroios"},
    {"formato":"Prox","loja":"A60-MA 25 Abril, Cascais"},
    {"formato":"Prox","loja":"A62-MA Dr António Elvas 26, Laranjeiro"},
    {"formato":"Prox","loja":"A63-MA República, Mafamude"},
    {"formato":"Prox","loja":"A64-MA Palma, Sta Maria Maior"},
    {"formato":"Prox","loja":"A65-MA Qta Lomba, Barreiro"},
    {"formato":"Prox","loja":"A66-MA Gago Coutinho, Venteira"},
    {"formato":"Prox","loja":"A67-MA Beira Mar, Armação Pêra"},
    {"formato":"Prox","loja":"A68-MA D Maria II, Cacém"},
    {"formato":"Prox","loja":"A69-MA Santos Leite, Cidade Maia"},
    {"formato":"Prox","loja":"A70-MA Poveiros, Porto Centro"},
    {"formato":"Prox","loja":"A71-MA Loios, Porto Centro"},
    {"formato":"Prox","loja":"A72-MA Diamantina, Paranhos"},
    {"formato":"Prox","loja":"A74-MA 23, Espinho"},
    {"formato":"Prox","loja":"A75-MA Sá Bandeira, Porto Centro"},
    {"formato":"Prox","loja":"A76-MA Conde, S Mamede Infesta"},
    {"formato":"Prox","loja":"A77-MA Heroísmo, Bonfim"},
    {"formato":"Prox","loja":"A78-MA Nova Corujeira, Campanhã"},
    {"formato":"Super","loja":"A79-SU Nova Laborim, Mafamude"},
    {"formato":"Prox","loja":"A80-MA Dr José Lencastre, Paços Ferreira"},
    {"formato":"Prox","loja":"A81-MA 5 Outubro, Ramalde"},
    {"formato":"Prox","loja":"A82-MA Cruzinha, Abrigada"},
    {"formato":"Prox","loja":"A83-MA João Batista Correia, Cast Ribatejo"},
    {"formato":"Prox","loja":"A85-MA Coração Maria, Cacém"},
    {"formato":"Prox","loja":"A86-MA Marquês Pombal, Sobral Monte Agraço"},
    {"formato":"Prox","loja":"A87-MA 5 Outubro, Aljustrel"},
    {"formato":"Prox","loja":"A88-MA Agostinho Neto, Sobreda"},
    {"formato":"Prox","loja":"A89-MA Rosa Falcão, Ansião"},
    {"formato":"Prox","loja":"A90-MA Foros Amora, Amora"},
    {"formato":"Prox","loja":"A91-MA 9 Julho, Venda Pinheiro"},
    {"formato":"Prox","loja":"A92-MA Sta Apolónia, Recarei"},
    {"formato":"Prox","loja":"A93-MA Pinheiro, Póvoa Varzim"},
    {"formato":"Prox","loja":"A95-MA Povoença, Areosa"},
    {"formato":"Prox","loja":"A96-MA D Nuno Álvares Pereira, Almada"},
    {"formato":"Prox","loja":"A97-MA Lusíadas, Alcântara"},
    {"formato":"Prox","loja":"A98-MA Mário Sacramento, Corroios"},
    {"formato":"Prox","loja":"A99-MA Alfredo Silva, Barreiro"},
    {"formato":"Prox","loja":"B01-MA Carlos Mardel, Arroios"},
    {"formato":"Prox","loja":"B02-MA Aquiles Machado, Beato"},
    {"formato":"Prox","loja":"B03-MA Afonso III, Penha França"},
    {"formato":"Prox","loja":"B04-MA Heróis Liberdade, Massamá"},
    {"formato":"Prox","loja":"B06-MA Bento Jesus Caraça 166, S Sebastião"},
    {"formato":"Prox","loja":"B07-MA Infante D Augusto, Amora"},
    {"formato":"Prox","loja":"B08-MA Gago Coutinho, Cascais"},
    {"formato":"Prox","loja":"B10-MA Mário Graça, Rio Mouro"},
    {"formato":"Prox","loja":"B11-MA Guilherme Kjolner, Amora"},
    {"formato":"Prox","loja":"B12-MA Luís Camões, Pinhal Novo"},
    {"formato":"Prox","loja":"B13-MA Cabo Verde, Prior Velho"},
    {"formato":"Prox","loja":"B14-MA Brasil, Alvalade"},
    {"formato":"Prox","loja":"B15-MA Miguel Bombarda, Queluz"},
    {"formato":"Prox","loja":"B17-MA Manuel Alpedrinha, Venteira"},
    {"formato":"Prox","loja":"B18-MA Ulisses Alves, Sintra Centro"},
    {"formato":"Prox","loja":"B19-MA D Dinis, Odivelas"},
    {"formato":"Prox","loja":"B20-MA Alexandre Ferreira, Lumiar"},
    {"formato":"Prox","loja":"B21-MA Bons Amigos, Agualva"},
    {"formato":"Prox","loja":"B22-MA Penha França, Penha França"},
    {"formato":"Prox","loja":"B23-MA Cristóvão Gama, Águas Livres"},
    {"formato":"Prox","loja":"B24-MA Tristão Vaz, Alfragide"},
    {"formato":"Prox","loja":"B25-MA D Filipa Vilhena, Areeiro"},
    {"formato":"Prox","loja":"B26-MA Cidade Salazar, Olivais"},
    {"formato":"Prox","loja":"B27-MA Liberdade, Encosta Sol"},
    {"formato":"Prox","loja":"B28-MA António Maria Pais, Moscavide"},
    {"formato":"Prox","loja":"B29-MA Sacadura Cabral, Areeiro"},
    {"formato":"Prox","loja":"B30-MA Circular Sul, Olivais"},
    {"formato":"Prox","loja":"B31-MA Cidade Viseu, Camarate"},
    {"formato":"Prox","loja":"B32-MA Eng Ferreira Dias, Marvila"},
    {"formato":"Prox","loja":"B33-MA Dr Francisco Sousa Tavares, Algueirão"},
    {"formato":"Prox","loja":"B34-MA José Conceição Nunes, Vale Amoreira"},
    {"formato":"Prox","loja":"B35-MA Bela Vista, Caparica"},
    {"formato":"Prox","loja":"B36-MA Dr João Silva, Santiago Cacém"},
    {"formato":"Prox","loja":"B37-MA Domingos Rodrigues Pablo, Sines"},
    {"formato":"Super","loja":"B38-SU 24 Setembro, Vialonga"},
    {"formato":"Prox","loja":"B39-MA Quintas, Caparica"},
    {"formato":"Prox","loja":"B40-MA José Gomes Monteiro, Odivelas"},
    {"formato":"Prox","loja":"B41-MA Mouzinho Albuquerque, Águas Livres"},
    {"formato":"Prox","loja":"B42-MA General Humberto Delgado, Mina Água"},
    {"formato":"Prox","loja":"B43-MA Combatentes Grande Guerra, Gondomar"},
    {"formato":"Prox","loja":"B44-MA Direita Massamá, Massamá"},
    {"formato":"Prox","loja":"B45-MA Ovar, Marvila"},
    {"formato":"Prox","loja":"B47-MA Marquês Sá Bandeira, Avenidas Novas"},
    {"formato":"Prox","loja":"B48-MA Almirante Barroso, Arroios"},
    {"formato":"Prox","loja":"B50-MA Ricardo Reis, Odivelas"},
    {"formato":"Prox","loja":"B51-MA Rui Gomes Silva, Chamusca"},
    {"formato":"Prox","loja":"B52-MA Rui Costa Lopes, Silveira"},
    {"formato":"Prox","loja":"B53-MA Est Benfica 212, S Domingos Benfica"},
    {"formato":"Prox","loja":"B54-MA Luciano Cordeiro, Sto António"},
    {"formato":"Prox","loja":"B55-MA Dr João Santos, Odivelas"},
    {"formato":"Prox","loja":"B56-MA Fontes Pereira Melo, Avenidas Novas"},
    {"formato":"Prox","loja":"B57-MA Almirante Reis 114, Arroios"},
    {"formato":"Prox","loja":"B58-MA Lapa, Estrela"},
    {"formato":"Prox","loja":"B59-MA Helena Vaz Silva, Lumiar"},
    {"formato":"Prox","loja":"B60-MA Virgílio Correia, S Domingos Benfica"},
    {"formato":"Super","loja":"B61-SU Dr Virgílio Vieira Cunha, Leiria"},
    {"formato":"Super","loja":"B62-SU Pau Queimado, Montijo"},
    {"formato":"Super","loja":"B63-SU Dias Neiva, Torres Vedras"},
    {"formato":"Super","loja":"B64-SU D João IV, Abrantes"},
    {"formato":"Super","loja":"B65-SU Est Salgueiro, Castelo Branco"},
    {"formato":"Super","loja":"B66-SU Timor Lorosae, Caldas Rainha"},
    {"formato":"Super","loja":"B67-SU Casal Queimado, Cascais"},
    {"formato":"Super","loja":"B68-SU Porto Pesca, Peniche"},
    {"formato":"Prox","loja":"B70-MA Dona Mariana Vitória, Belas"},
    {"formato":"Super","loja":"B71-SU Est Mem Martins 6, Algueirão"},
    {"formato":"Super","loja":"B72-SU Bombeiros Voluntários, Moura"},
    {"formato":"Super","loja":"B74-SU Est S Domingos, Santarém"},
    {"formato":"Super","loja":"B75-SU Alto Camacha, Ericeira"},
    {"formato":"Super","loja":"B76-SU Dr José Henr Vareda, Marinha Grande"},
    {"formato":"Super","loja":"B77-SU Dr António Sousa Dias, Benavente"},
    {"formato":"Super","loja":"B78-SU Vale Paraíso, Albufeira"},
    {"formato":"Super","loja":"B79-SU Operários Conserveiros, Quelfes"},
    {"formato":"Super","loja":"B80-SU N246, Portalegre"},
    {"formato":"Super","loja":"B81-SU Dr Henrique Barros, Algueirão"},
    {"formato":"Super","loja":"B82-SU Máximo Silva, Rio Mouro"},
    {"formato":"Super","loja":"B83-SU Baluarte, Bacelo"},
    {"formato":"Super","loja":"B84-SU Forças Armadas, Sintra Centro"},
    {"formato":"Super","loja":"B85-SU Mercado Santos, Avenidas Novas"},
    {"formato":"Super","loja":"B86-SU Luís Camões, Águas Livres"},
    {"formato":"Prox","loja":"B87-MA Fernão Magalhães, Bonfim"},
    {"formato":"Prox","loja":"B88-MA 25 Abril, Ílhavo"},
    {"formato":"Prox","loja":"B89-MA Est Benfica 402, S Domingos Benfica"},
    {"formato":"Prox","loja":"B90-MA Pedreiras, Belém"},
    {"formato":"Super","loja":"B92-SU NSra Piedade, Alfena"},
    {"formato":"Prox","loja":"B93-MA Lugar Qta Granja, Carquere"},
    {"formato":"Prox","loja":"B94-MA Noruega, Vila Pouca Aguiar"},
    {"formato":"Prox","loja":"B95-MA Camões, Campelo"},
    {"formato":"Super","loja":"B96-SU Francisco Sá Carneiro, Rebordosa"},
    {"formato":"Prox","loja":"B97-MA Direita Dafundo, Carnaxide"},
    {"formato":"Prox","loja":"B98-MA Dr Ricardo Jorge, Porto Centro"},
    {"formato":"Prox","loja":"B99-MA Alfredo Cunha, Matosinhos Centro"},
    {"formato":"Servicos","loja":"Sede"}
  ],
  assistentes: [
    {
        "formato": "*",
        "loja": "*",
        "nome": "AuchanAI",
        "label": "AuchanAI",
        "url": "https://genai-platform.auchan.com/#/chat",
        "icone": "AuchanAI.jpg"
    },
    {
        "formato": "*",
        "loja": "*",
        "nome": "Coach",
        "label": "Coach",
        "url": "https://genai-platform.auchan.com",
        "icone": "Coach.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Contratos",
        "label": "Contratos",
        "url": "https://genai-platform.auchan.com/#/share/6e5f9252-e132-4d4c-a308-3fc7ee54fddf",
        "icone": "Contratos.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "012-Almada",
        "nome": "Echo",
        "label": "Echo",
        "url": "https://genai-platform.auchan.com/#/share/e706fd1e-b79b-42cd-b369-14ac335302d5",
        "icone": "Echo.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "018-Paço de Arcos",
        "nome": "Echo",
        "label": "Echo",
        "url": "https://genai-platform.auchan.com/#/share/e706fd1e-b79b-42cd-b369-14ac335302d5",
        "icone": "Echo.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Estudos(Compra)",
        "label": "Estudos(Compra)",
        "url": "URL",
        "icone": "Estudos-Compra.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Estudos(Oferta)",
        "label": "Estudos(Oferta)",
        "url": "https://genai-platform.auchan.com/#/share/f50fe60a-7306-4427-8de9-7bf15f4643db",
        "icone": "Estudos-Oferta.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Estudos(Operações)",
        "label": "Estudos(Operações)",
        "url": "https://genai-platform.auchan.com/#/share/598e9e9e-b591-4705-bdbe-52f19d7eedc4",
        "icone": "Estudos-Operações.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "019-Coina",
        "nome": "Faisca",
        "label": "Faisca",
        "url": "https://genai-platform.auchan.com/#/share/a389a983-adb8-42ab-b72e-31c56bfab267",
        "icone": "Faisca.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "027-Setúbal",
        "nome": "Faisca",
        "label": "Faisca",
        "url": "https://genai-platform.auchan.com/#/share/a389a983-adb8-42ab-b72e-31c56bfab267",
        "icone": "Faisca.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Ficha de Produto",
        "label": "Ficha de Produto",
        "url": "https://genai-platform.auchan.com/#/share/cb9d6925-ef73-41f2-a2ac-e92c4d4893c5",
        "icone": "Ficha-de-Produto.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Folhetos",
        "label": "Folhetos",
        "url": "https://genai-platform.auchan.com/#/share/d40417b7-1d75-48d5-b8b1-48e5b318d6db",
        "icone": "Folhetos.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "*",
        "nome": "Jade",
        "label": "Jade",
        "url": "https://genai-platform.auchan.com/#/share/dcd986cf-ca6e-41df-bb4e-8dc387eb0906",
        "icone": "Jade.jpg"
    },
    {
        "formato": "Prox",
        "loja": "*",
        "nome": "MySafira",
        "label": "MySafira",
        "url": "https://genai-platform.auchan.com/#/share/e7f3fdbd-7456-40d6-8f00-02c0f47c6344",
        "icone": "MySafira.jpg"
    },
    {
        "formato": "Super",
        "loja": "*",
        "nome": "MySafira",
        "label": "MySafira",
        "url": "https://genai-platform.auchan.com/#/share/e7f3fdbd-7456-40d6-8f00-02c0f47c6344",
        "icone": "MySafira.jpg"
    },
    {
        "formato": "Servicos",
        "loja": "*",
        "nome": "Reunião com Fornecedor",
        "label": "Reunião com Fornecedor",
        "url": "https://genai-platform.auchan.com/#/share/a73adc68-2cd2-4a63-bf23-0747d914d5a5",
        "icone": "Reunião-Fornecedor.jpg"
    },
    {
        "formato": "*",
        "loja": "*",
        "nome": "Violeta",
        "label": "Violeta",
        "url": "https://genai-platform.auchan.com/#/share/17fb9d00-4091-4c3f-91ac-6dfebabfecd6",
        "icone": "Violeta.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "018-Paço de Arcos",
        "nome": "Wally",
        "label": "Wally",
        "url": "https://genai-platform.auchan.com/#/share/7f236c5d-c8de-4e6f-a8a3-19a542f68c51",
        "icone": "wally-512.jpg"
    },
    {
        "formato": "Hiper",
        "loja": "012-Almada",
        "nome": "Wally",
        "label": "Wally",
        "url": "https://genai-platform.auchan.com/#/share/e8eedf3c-7c3c-4eb4-95f0-8a583ac828fb",
        "icone": "wally-512.jpg"
    }
  ]
};
